name: Security - Checkmarx One (CLI)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  checkmarx-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Checkmarx CLI (via script oficial)
        run: |
          curl -L https://raw.githubusercontent.com/Checkmarx/ast-cli/main/install.sh | bash

      - name: Run Checkmarx Scan
        run: |
          cx scan create \
            --base-uri https://eu.ast.checkmarx.net \
            --tenant beta_nova8 \
            --client-id ${{ secrets.CX_CLIENT_ID }} \
            --client-secret ${{ secrets.CX_CLIENT_SECRET }} \
            --project-name "Desafio Time B - mern-amazona-docker" \
            --branch ${{ github.ref }} \
            --scan-types sast,sca,iac-security \
            --report-format sarif \
            --output-path .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cx_result.sarif
