name: Test Checkmarx CLI

on:
  push:

jobs:
  test-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Checkmarx CLI (debug)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            checkmarx/ast-cli:latest version
